config/routes.rb
Rails.application.routes.draw do
  

  get 'relationships/create'
  get 'relationships/destroy'
  get 'transit/home'
  devise_for :users, controllers:{ registrations: 'registrations' } do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :skills do
    resources :users
  end
  resources :users, only: [:show], param: :slug
  resources :users, only: %i[show index], param: :slug do 
    resources :posts
    resources :skills, only: %i[create]
  end
  resources :comments do 
    resources :users
    resources :posts
  end

  authenticated :user do
    root 'posts#index', as: :authenticated_root
  end
  resources :users, only: [:index]
  resources :posts do
    resources :users
    resources :careers
    resources :comments
    resources :skills
    member do
      put "like" => "posts#vote"
    end
  end

  resources :relationships, only: [:create, :destroy] do
    resources :users
    resources :posts
  end
  get "/:user_slug/connections", to: "users#user_connections", as: "user_connections"
  get "/current_user_skills", to: "users#current_user_skills"
  root :to => "welcome#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  has_rich_text :content
  validates :title, length: {maximum: 50}
  belongs_to :user
  belongs_to :career
  has_many :skills
  has_many :comments
  scope :most_recent, -> { order(created_at: :desc) }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update edit destroy vote]
  before_action :authenticate_user!, only: [:index, :new, :create, :edit, :update, :show, :destory, :vote]
  respond_to :js, :json, :html
  def index
    
    @posts = Post.all.includes(:user, :comments, :likes, :career, :following).most_recent
    @posts_career = Post.all.includes(:career).most_recent
    @user_posts = current_user.posts.most_recent
    @career_post = current_user.career.posts
    @comments = current_user.comments.most_recent
    @comments_new = Comment.new
    @posts = Post.most_recent
  end

  def show
   @post_comments = @post.comments.includes(:user).most_recent.limit(5)
  end

  def create
    @post = current_user.posts.build(post_params)
    if  @post.save
      redirect_to posts_path
      flash[:notice] = 'Posted successfully'
    else
      flash[:alert] = 'Not posted,must be 10 world min, try again!'
      redirect_to posts_path
    end
  end

  def edit; end

  def update
    @post.update(post_params)
    redirect_to posts_path
  end

  def vote
    if !current_user.liked? @post
      @post.liked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js { render layout: false }
      end
    elsif current_user.liked? @post
      @post.unliked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js { render layout: false }
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:title,:content,:comment_id,:image,:user_slug, :created_at, :skill_id, :career_id)
  end


  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="container">
  <!-- Button trigger modal -->

</div>

<div class="container"> 
  <div class="d-flex justify-content-center py-3">
    <button type="button" class="post w-50" data-bs-toggle="modal" data-bs-target="#exampleModal">
      <span class="text-muted text-left">Post here</span>
    </button>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Post something</h5>
      </div>
      <div class="modal-body">
        <%= form_for Post.new, :url => posts_path(), :method => :post do |f| %>
        <%= f.text_field :title, :placeholder => "Title", class:"w-100 text" %><br><br>
    <%= f.rich_text_area :content, placeholder: "Post here", class:"w-100 text",cols: 60, rows: 15 %><br>
    
        <%= f.select(:career_id, Career.all.collect {|u| [u.field, u.id]}, {:prompt => 'Tag to a career'},{class: "form-control selectpicker",data: {"live-search": true}}) %><br><br>
        <%= f.select :skill_id, options_for_select(Skill.all.collect{ |u| [u.name, u.id] }), {prompt:"Tag to skill"}, {class: "form-control selectpicker", data: {"live-search": true}}%>
    </div><br>
      <div class="modal-footer">
        <%= button_tag( :class => "btn btn-primary w-100") do %>
            <i class="fas fa-comment-alt"></i> Post
        <% end %>
        <%end%>
      </div>
    </div>
  </div>
</div>
</div>

<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <a class="nav-link active" id="home-tab" data-bs-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true"><%= current_user.career.field.capitalize %> posts</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link" id="profile-tab" data-bs-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">My connections</a>
  </li>
  
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
    
    <% @posts_career.each do |post| %>
      <% if post.career_id == current_user.career.id %>
       <div class="container">
    <div class="d-flex justify-content-center row">
        <div class="col-md-8">
            <div class="feed p-2">
                <div class="bg-white border mt-2">
                    <div>
                        <div class="d-flex flex-row justify-content-between align-items-center p-2 border-bottom">
                        <%= link_to post_user_path(post, post.user), :action => 'go' do %>
                            <div class="d-flex flex-row align-items-center feed-text px-2"><%= image_tag user_avatar(post.user), class:"border rounded-circle", width:"45"%>
                                <div class="d-flex flex-column flex-wrap ml-2"><span class="font-weight-bold text-muted"><%= post.user.username %></span><span class="text-black-50 time">40 minutes ago</span></div>
                            </div>
                        <%end%>
                            <div class="feed-icon px-2"><i class="fa fa-ellipsis-v text-black-50"></i></div>
                        </div>
                    </div>
                    <div class="p-5 px-3">
                      <p><%= post.content %></p>
                      <span>
                        <%= link_to like_post_path(post),class:"like-btn", method: :put, remote: :true do%>
                                <span><i class="fas fa-thumbs-up"></i></span>
                                <span class="badge btn-colour-1"><%= post.get_upvotes.size %></span>
                        <% end %>
                        
                      </span>
                    </div>
                      
                        <div class="accordion-item">
                          <h2 class="accordion-header" id="headingOne">
                          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            <i class="fas fa-comment-alt"></i>
                              <span class="mx-2">Comments</span> <span class="badge btn-colour-1"><%= post.comments.size %></span>
                          </button>
                          </h2>
                          <div id="collapseOne" class="accordion-collapse collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                            <div class="accordion-body w-100">
                            
                              <%= form_with(model: [post, @comments_new], local: true) do |f|%>
                              <%= f.text_area :text, placeholder: "Add a comment", class:"w-100 text" %>
                           
                            <%= f.submit "Comment", class:"btn btn-colour-1" %>
                            
                        <%end%>
                        <div class="p-3">
                          <% post.comments.limit(5).most_recent.each do |c| %>
                            <div class="d-flex flex-row align-items-start p-2">
                              <div class="">
                              <%= link_to comment_user_path(c, c.user), :action => 'go' do %>
                                <%= image_tag user_avatar(post.user), class:"border rounded-circle", width:"45"%>
                              
                            <%end%>
                              </div>
                              <div class="">
                              <p class="text-dark p-3 comment-bg-color">
                              <%= c.text %>
                            </p>
                              </div>
                            </div>
                           
                          <%end%>
                          <div class="text-center">
                          <%= link_to post_path(post), class:"text-secondary" do %>
                            <i class="fas fa-comment-alt"></i>
                            <span class="">View post and all comments</span>
                          <% end %>
                          </div>
                        </div>
                      </div>
             
                      </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    </div>
    <% end %>
    <%end%>
  </div>
  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
         <% current_user.following.each do |followed| %>
          <% followed.posts.most_recent.each do |post| %>
       <div class="container">
    <div class="d-flex justify-content-center row">
        <div class="col-md-8">
            <div class="feed p-2">
                <div class="bg-white border mt-2">
                    <div>
                        <div class="d-flex flex-row justify-content-between align-items-center p-2 border-bottom">
                        <%= link_to post_user_path(post, post.user), :action => 'go' do %>
                            <div class="d-flex flex-row align-items-center feed-text px-2"><%= image_tag user_avatar(post.user), class:"border rounded-circle", width:"45"%>
                                <div class="d-flex flex-column flex-wrap ml-2"><span class="font-weight-bold text-muted"><%= post.user.username.capitalize %></span><span class="text-black-50 time">40 minutes ago</span></div>
                            </div>
                        <%end%>
                            <div class="feed-icon px-2"><i class="fa fa-ellipsis-v text-black-50"></i></div>
                        </div>
                    </div>
                    <div class="p-5 px-3">
                      <p><%= post.content %></p>
                      <span>
                        <%= link_to like_post_path(post),class:"like-btn", method: :put, remote: :true do%>
                                <span><i class="fas fa-thumbs-up"></i></span>
                                <span class="badge btn-colour-1"><%= post.get_upvotes.size %></span>
                        <% end %>
                        
                      </span>
                    </div>
                      
                        <div class="accordion-item">
                          <h2 class="accordion-header" id="headingOne">
                          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            <i class="fas fa-comment-alt"></i>
                              <span class="mx-2">Comments</span> <span class="badge btn-colour-1"><%= post.comments.size %></span>
                          </button>
                          </h2>
                          <div id="collapseOne" class="accordion-collapse collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                            <div class="accordion-body w-100">
                            
                              <%= form_with(model: [post, @comments_new], local: true) do |f|%>
                              <%= f.text_area :text, placeholder: "Comment here", class:"w-100 text" %>
                           
                            <%= f.submit "Comment", class:"btn-colour-1" %>
                        <%end%>
              </div>
                        
                      </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    </div>
    <%end%>
    <%end%>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
    <div class="row">
        
        <div class="col-md-8 pt-5">
        <div class="d-flex align-items-center justify-content-between border-bottom py-3">
            <div class="">
            <%= link_to user_path(@post.user), :action => 'go' do  %>
                <%= image_tag user_avatar(@post.user), class:"img-responsive rounded-circle border shadow",width:"45"%>
            <%end%>
             </div>
            <span class="text-muted">Posted: <%= @post.created_at.strftime("%B %Y") %></span>
        </div>
        <h1>
                <%= @post.title %>
            </h1>
            <p class="pt-5">
                <%= @post.content %>
            </p>
           
        </div>
        <div class="col-md-4 pt-5 border-start">
            <%@post_comments.each do |comment|%>
                <div class="comment-widgets m-b-20">
                    <div class="d-flex justify-content-between comment-row">
                        <div class="">
                            <%= link_to user_path(comment.user), :action => 'go' do  %>
                                <%= image_tag user_avatar(comment.user), class:"img-responsive rounded-circle border shadow",width:"45"%>
                            <%end%>
                        </div>
                        <div class="comment-text w-100">
                            <div class="comment-footer"> <span class="text-muted"><%= comment.created_at.strftime("%B %Y") %></span> </div>
                            <p class="font-medium"><%= comment.text.capitalize  %></p>
                        </div>
                    </div>
                    </div>
            <%end%>
        </div>
    </div>
</div>

app/views/posts/vote.js.erb
 <% if current_user.liked? @post %>
    $('.like-btn').addClass('liked');
<%else%>
    $('.like-btn').addClass('like-btn');
<%end%>
('.likes-count').html("<%= @post.get_upvotes.size %>");